//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int id_acc { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> id_per { get; set; }
        public string full_name { get; set; }
        public Nullable<bool> acc_ban { get; set; }
    
        public virtual permision permision { get; set; }
    }
}
