//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule_detail
    {
        public int id { get; set; }
        public string id_tea { get; set; }
        public Nullable<int> id_subj { get; set; }
        public Nullable<int> id_room { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> lesson { get; set; }
        public Nullable<int> num_of_less { get; set; }
    
        public virtual room room { get; set; }
        public virtual subject subject { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
