//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public int id_status { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> lesson { get; set; }
        public Nullable<int> id_comp { get; set; }
        public string detail { get; set; }
    
        public virtual computer computer { get; set; }
    }
}
